// <auto-generated />
using System;
using FizzBuzz.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FizzBuzz.Migrations
{
    [DbContext(typeof(FizzBuzzDbContext))]
    [Migration("20190317172927_CreateDatabase")]
    partial class CreateDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854");

            modelBuilder.Entity("FizzBuzz.Entities.FizzBuzzHistory<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<bool>("Error");

                    b.Property<string>("IP");

                    b.Property<int>("InputNumber");

                    b.Property<string>("Message");

                    b.Property<DateTime>("Modified");

                    b.HasKey("Id");

                    b.ToTable("FizzBuzzHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
